### ISSUE TITLE
创建challenge时切换为CTF-Fish类型无反应

### ISSUE THREAD

**Issue by Le0nsec** [LioTree/CTFd-Fish#1]
请问您是什么版本呢，我用CTFd2.5.0版本使用您的插件，但是在创建challenge时切换为CTF-Fish类型没有任何反应，没有出现url栏和passcode栏。

**Comment by Le0nsec** [comment]
相关js都响应为404

**Comment by Le0nsec** [comment]
找到原因了emmm，git clone下来的文件夹名称是CTFd-Fish，但是索引的目录是CTFd_Fish。。。。

**Comment by LioTree** [comment]
> 找到原因了emmm，git clone下来的文件夹名称是CTFd-Fish，但是索引的目录是CTFd_Fish。。。。

啊不好意思一直没看到。。我把项目名改成CTFd_Fish了，谢谢提醒-_-
